"use strict";(self.webpackChunksync_powershell=self.webpackChunksync_powershell||[]).push([[736,2618],{3905:(e,t,n)=>{n.d(t,{Zo:()=>c,kt:()=>h});var r=n(7294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function a(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?a(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):a(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,r,o=function(e,t){if(null==e)return{};var n,r,o={},a=Object.keys(e);for(r=0;r<a.length;r++)n=a[r],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(r=0;r<a.length;r++)n=a[r],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var s=r.createContext({}),p=function(e){var t=r.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},c=function(e){var t=p(e.components);return r.createElement(s.Provider,{value:t},e.children)},d="mdxType",m={inlineCode:"code",wrapper:function(e){var t=e.children;return r.createElement(r.Fragment,{},t)}},u=r.forwardRef((function(e,t){var n=e.components,o=e.mdxType,a=e.originalType,s=e.parentName,c=l(e,["components","mdxType","originalType","parentName"]),d=p(n),u=o,h=d["".concat(s,".").concat(u)]||d[u]||m[u]||a;return n?r.createElement(h,i(i({ref:t},c),{},{components:n})):r.createElement(h,i({ref:t},c))}));function h(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var a=n.length,i=new Array(a);i[0]=u;var l={};for(var s in t)hasOwnProperty.call(t,s)&&(l[s]=t[s]);l.originalType=e,l[d]="string"==typeof e?e:o,i[1]=l;for(var p=2;p<a;p++)i[p]=n[p];return r.createElement.apply(null,i)}return r.createElement.apply(null,n)}u.displayName="MDXCreateElement"},4391:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>s,contentTitle:()=>i,default:()=>m,frontMatter:()=>a,metadata:()=>l,toc:()=>p});var r=n(7462),o=(n(7294),n(3905));const a={slug:"/ADR007",title:"ADR007 Exception Handling",tags:["ADR"]},i=void 0,l={unversionedId:"ADR/ADR007",id:"ADR/ADR007",title:"ADR007 Exception Handling",description:"TITLE: ADR 007 - Exception Handling",source:"@site/docs/ADR/ADR007.md",sourceDirName:"ADR",slug:"/ADR007",permalink:"/help/docs/ADR007",draft:!1,tags:[{label:"ADR",permalink:"/help/docs/tags/adr"}],version:"current",frontMatter:{slug:"/ADR007",title:"ADR007 Exception Handling",tags:["ADR"]},sidebar:"tutorialSidebar",previous:{title:"ADR006 Deploy",permalink:"/help/docs/ADR006"},next:{title:"UseCase",permalink:"/help/docs/category/usecase"}},s={},p=[{value:"TITLE: ADR 007 - Exception Handling",id:"title-adr-007---exception-handling",level:2},{value:"Context and Problem Statement",id:"context-and-problem-statement",level:2},{value:"Decision Drivers",id:"decision-drivers",level:2},{value:"Decision Outcome",id:"decision-outcome",level:2},{value:"Positive Consequences",id:"positive-consequences",level:2},{value:"Negative Consequences",id:"negative-consequences",level:2},{value:"Pros and Cons of the Options",id:"pros-and-cons-of-the-options",level:2},{value:"Pros of Using Custom Exceptions",id:"pros-of-using-custom-exceptions",level:3},{value:"Cons of Using Custom Exceptions",id:"cons-of-using-custom-exceptions",level:3}],c={toc:p},d="wrapper";function m(e){let{components:t,...n}=e;return(0,o.kt)(d,(0,r.Z)({},c,n,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("h2",{id:"title-adr-007---exception-handling"},"TITLE: ADR 007 - Exception Handling"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},"Status: accepted ")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},"Deciders: ",'["Andrei Ignat"]')),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},"Date: ","[2023-11-05]"))),(0,o.kt)("h2",{id:"context-and-problem-statement"},"Context and Problem Statement"),(0,o.kt)("p",null,"In every program we need to handle the unexpected situations. One of those are configuration errors.\nOthers are network errors, database errors, etc. However, there are many situations where the errors are of our own - like a bug in the code, errors in the database and so on..."),(0,o.kt)("h2",{id:"decision-drivers"},"Decision Drivers"),(0,o.kt)("p",null,"In order to make a difference between the errors that are of our own and the errors that are not of our own, we need to have a way to handle them differently. That's why a custom exception is needed."),(0,o.kt)("h2",{id:"decision-outcome"},"Decision Outcome"),(0,o.kt)("p",null,'Chosen option: "Use a custom exception" every time when the error is of our own. Also, use a custom exception when the error is not of our own, but we want to handle it differently. '),(0,o.kt)("h2",{id:"positive-consequences"},"Positive Consequences"),(0,o.kt)("p",null,"Internal errors are handled differently than external errors. And some corrective measures can be applied."),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Domain-Specific Errors:")," When you have errors that are specific to your business logic or domain, custom exceptions can be used to represent these errors.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Complex Error Handling:")," If your application has complex error handling requirements, custom exceptions can be used to differentiate between different types of errors.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Enhanced Error Information:")," If you need to include additional information in your exceptions (like error codes or additional context), custom exceptions can be used.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Control Flow:")," In some cases, custom exceptions can be used as a form of control flow. This is generally discouraged, but there are some scenarios where it can be useful.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Third-Party Library Errors:")," If you're using a third-party library that throws generic exceptions, you might want to catch those and throw your own custom exceptions instead. This can make your error handling code more consistent and easier to understand."))),(0,o.kt)("h2",{id:"negative-consequences"},"Negative Consequences"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Loss of Inner Exception:")," If not handled properly, the inner exception that caused the custom exception might be lost, making it harder to debug the issue - or should be added to help the developer to understand the error.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Increased Development Time:")," Creating and maintaining custom exceptions can increase development time.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Potential for Misuse:")," Custom exceptions can be misused or overused, leading to unnecessary complexity.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Learning Curve:")," Other developers unfamiliar with the custom exceptions might have a learning curve to understand them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Dependency:")," If the custom exceptions are part of a library that is used across multiple projects, changes to the exceptions can impact all these projects."))),(0,o.kt)("h2",{id:"pros-and-cons-of-the-options"},"Pros and Cons of the Options"),(0,o.kt)("h3",{id:"pros-of-using-custom-exceptions"},"Pros of Using Custom Exceptions"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("strong",{parentName:"li"},"Specificity:")," Custom exceptions provide more specific error information, making it easier to understand and handle the error."),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("strong",{parentName:"li"},"Control:")," They allow for more control over error handling, as you can create different exceptions for different error conditions."),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("strong",{parentName:"li"},"Clarity:")," They can make the code more readable and maintainable, as the exception names can reflect the error conditions they represent.")),(0,o.kt)("h3",{id:"cons-of-using-custom-exceptions"},"Cons of Using Custom Exceptions"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("strong",{parentName:"li"},"Complexity:")," Creating custom exceptions can add complexity to the code, especially if overused."),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("strong",{parentName:"li"},"Maintenance:")," They require more maintenance. If the error conditions change, the custom exceptions also need to be updated."),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("strong",{parentName:"li"},"Standardization:")," Using standard exceptions can sometimes be more straightforward and less error-prone, as they are widely recognized and understood by most developers.")))}m.isMDXComponent=!0},8686:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>l,default:()=>u,frontMatter:()=>i,metadata:()=>s,toc:()=>c});var r=n(7462),o=(n(7294),n(3905)),a=n(4391);const i={},l="Added deployment",s={permalink:"/help/blog/2023/10/31/index",source:"@site/blog/2023-10-31/index.md",title:"Added deployment",description:"After this ADR",date:"2023-10-31T00:00:00.000Z",formattedDate:"October 31, 2023",tags:[],readingTime:1.21,hasTruncateMarker:!0,authors:[],frontMatter:{},prevItem:{title:"Added CPM and ProjProperties",permalink:"/help/blog/2023/11/01/index"},nextItem:{title:"Added deployment",permalink:"/help/blog/2023/10/30/index"}},p={authorsImageUrls:[]},c=[],d={toc:c},m="wrapper";function u(e){let{components:t,...n}=e;return(0,o.kt)(m,(0,r.Z)({},d,n,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("p",null,"After this ADR "),(0,o.kt)("hr",null),(0,o.kt)(a.default,{mdxType:"ADR007"}),(0,o.kt)("p",null,"I have created the custom exception base class"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"namespace syncPowershellException;\npublic abstract class BaseAppException: Exception\n{\n    public BaseAppException(string message): base(message)\n    {\n        \n    }\n    public BaseAppException(string message, Exception inner)\n        : base(message, inner)\n    {\n    }\n\n}\n")),(0,o.kt)("p",null,"I resisted to the temptation to create a custom exception for every error.  Example : "),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"ArgumentNullException.ThrowIfNull(data);\n")),(0,o.kt)("p",null,"should be left as it is."),(0,o.kt)("p",null,"Instead ,look at this example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},'public async Task<DataToBeSent> GetData()\n{\n    var powershell7Profile =environment.GetFolderPath( Environment.SpecialFolder.MyDocuments );\n    powershell7Profile = path.Combine(powershell7Profile, "WindowsPowerShell", "Microsoft.PowerShell_profile.ps1");\n    DataToBeSent dataToBeSent = new ();\n    dataToBeSent.UserName=environment.UserName;\n    dataToBeSent.PC = environment.MachineName;\n    if (file.Exists(powershell7Profile))\n    {\n        dataToBeSent.Powershell = await file.ReadAllTextAsync(powershell7Profile, CancellationToken.None);\n        dataToBeSent.PowershellNumber = 7;\n    }\n    return dataToBeSent;\n}\n')),(0,o.kt)("p",null,"If the file does not exists , then an error must be thrown. "),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},'public class PowershellProfileNotExistsException : BaseAppException\n{\n    public readonly string fileName;\n\n    public PowershellProfileNotExistsException(string fileName) : base($"file {fileName} does not exists")\n    {\n        this.fileName = fileName;\n    }\n\n}\n')),(0,o.kt)("p",null,"And the code will be modified like this:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},'public async Task<DataToBeSent> GetData()\n{\n    var powershell7Profile =environment.GetFolderPath( Environment.SpecialFolder.MyDocuments );\n    powershell7Profile = path.Combine(powershell7Profile, "WindowsPowerShell", "Microsoft.PowerShell_profile.ps1");\n    DataToBeSent dataToBeSent = new ();\n    dataToBeSent.UserName=environment.UserName;\n    dataToBeSent.PC = environment.MachineName;\n    if (!file.Exists(powershell7Profile))\n        throw new PowershellProfileNotExistsException(powershell7Profile);\n        \n    dataToBeSent.Powershell = await file.ReadAllTextAsync(powershell7Profile, CancellationToken.None);\n    dataToBeSent.PowershellNumber = 7;\n    \n    \n    return dataToBeSent;\n}\n')),(0,o.kt)("p",null,"Also the test will be modified from"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"DataGatherer gatherer = new(en.Instance(), file.Instance(),path.Instance(), logger);\ndata = await gatherer.GetData();\ndata.Should().NotBeNull();\n")),(0,o.kt)("p",null,"to "),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"DataGatherer gatherer = new(en.Instance(), file.Instance(),path.Instance(), logger);\nvar X=async ()=> (await gatherer.GetData());\nawait X.Should().ThrowAsync<PowershellProfileNotExistsException>();\n")))}u.isMDXComponent=!0}}]);